# Generated by Django 5.1.7 on 2025-05-08 20:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_download'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='download',
            unique_together={('user', 'document')},
        ),
    ]
